"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class camera_cfg_t(object):
    __slots__ = ["gain", "exposure", "binning", "framerate", "exit_app"]

    def __init__(self):
        self.gain = 0
        self.exposure = 0
        self.binning = 0
        self.framerate = 0
        self.exit_app = 0

    def encode(self):
        buf = BytesIO()
        buf.write(camera_cfg_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiiii", self.gain, self.exposure, self.binning, self.framerate, self.exit_app))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != camera_cfg_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return camera_cfg_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = camera_cfg_t()
        self.gain, self.exposure, self.binning, self.framerate, self.exit_app = struct.unpack(">iiiii", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if camera_cfg_t in parents: return 0
        tmphash = (0xa9d746f8344af438) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if camera_cfg_t._packed_fingerprint is None:
            camera_cfg_t._packed_fingerprint = struct.pack(">Q", camera_cfg_t._get_hash_recursive([]))
        return camera_cfg_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

