"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mwt.header_t


class mini_rov_depth_t(object):
    __slots__ = ["header", "depth", "pressure"]

    def __init__(self):
        self.header = mwt.header_t()
        self.depth = 0.0
        self.pressure = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(mini_rov_depth_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == mwt.header_t._get_packed_fingerprint()
        self.header._encode_one(buf)
        buf.write(struct.pack(">dd", self.depth, self.pressure))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mini_rov_depth_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mini_rov_depth_t._decode_one(buf)

    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mini_rov_depth_t()
        self.header = mwt.header_t._decode_one(buf)
        self.depth, self.pressure = struct.unpack(">dd", buf.read(16))
        return self

    _decode_one = staticmethod(_decode_one)

    _hash = None

    def _get_hash_recursive(parents):
        if mini_rov_depth_t in parents: return 0
        newparents = parents + [mini_rov_depth_t]
        tmphash = (0x16e44850c90dda6a + mwt.header_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash = (((tmphash << 1) & 0xffffffffffffffff) + (tmphash >> 63)) & 0xffffffffffffffff
        return tmphash

    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mini_rov_depth_t._packed_fingerprint is None:
            mini_rov_depth_t._packed_fingerprint = struct.pack(">Q", mini_rov_depth_t._get_hash_recursive([]))
        return mini_rov_depth_t._packed_fingerprint

    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)
