"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mwt.stereo_image_t

import mwt.stereo_bounding_box_t

class stereo_image_with_boxes_t(object):
    __slots__ = ["stereo_boxes", "stereo_image"]

    __typenames__ = ["mwt.stereo_bounding_box_t", "mwt.stereo_image_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.stereo_boxes = mwt.stereo_bounding_box_t()
        self.stereo_image = mwt.stereo_image_t()

    def encode(self):
        buf = BytesIO()
        buf.write(stereo_image_with_boxes_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.stereo_boxes._get_packed_fingerprint() == mwt.stereo_bounding_box_t._get_packed_fingerprint()
        self.stereo_boxes._encode_one(buf)
        assert self.stereo_image._get_packed_fingerprint() == mwt.stereo_image_t._get_packed_fingerprint()
        self.stereo_image._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != stereo_image_with_boxes_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return stereo_image_with_boxes_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = stereo_image_with_boxes_t()
        self.stereo_boxes = mwt.stereo_bounding_box_t._decode_one(buf)
        self.stereo_image = mwt.stereo_image_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if stereo_image_with_boxes_t in parents: return 0
        newparents = parents + [stereo_image_with_boxes_t]
        tmphash = (0xd198bfb6c874318c + mwt.stereo_bounding_box_t._get_hash_recursive(newparents) + mwt.stereo_image_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if stereo_image_with_boxes_t._packed_fingerprint is None:
            stereo_image_with_boxes_t._packed_fingerprint = struct.pack(">Q", stereo_image_with_boxes_t._get_hash_recursive([]))
        return stereo_image_with_boxes_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", stereo_image_with_boxes_t._get_packed_fingerprint())[0]

