"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mwt.header_t

class string_t(object):
    __slots__ = ["header", "val"]

    def __init__(self):
        self.header = mwt.header_t()
        self.val = ""

    def encode(self):
        buf = BytesIO()
        buf.write(string_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.header._get_packed_fingerprint() == mwt.header_t._get_packed_fingerprint()
        self.header._encode_one(buf)
        __val_encoded = self.val.encode('utf-8')
        buf.write(struct.pack('>I', len(__val_encoded)+1))
        buf.write(__val_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != string_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return string_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = string_t()
        self.header = mwt.header_t._decode_one(buf)
        __val_len = struct.unpack('>I', buf.read(4))[0]
        self.val = buf.read(__val_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if string_t in parents: return 0
        newparents = parents + [string_t]
        tmphash = (0xe82a35ae48fcbf5f+ mwt.header_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if string_t._packed_fingerprint is None:
            string_t._packed_fingerprint = struct.pack(">Q", string_t._get_hash_recursive([]))
        return string_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

